//:_____________________________________________________________________
//  astTF  |  Copyright (C) Ivan Mar (sOkam!)  |  GNU LGPLv3 or later  :
//:_____________________________________________________________________
/**
 * @fileoverview Script used to create the autogenerated files in the Samples folder
 * */
// @deps astTF
import * as F from './tools/files'

const dir = "samples/"

//______________________________________
// @section Samples: Readme File
//____________________________
const trg = dir+"readme.md"

const title_Root =
`# astTF Examples`
const descr_Root =
`Collection of valid \`astTF\` files representing the capabilities of the format.  `

const title_Minimal =
`## Minimal Examples`
const descr_Minimal =
``

const title_Basic =
`## Basic Examples`
const descr_Basic =
``


const Nl = '\n'
const TemplTODO = "- [TODO](./readme.md)"
function TemplEntry (file :string, descr :string) :string {
  return `- Sample [${file}](./${file}/) : ${descr}` }
const entries = [
  {file: "000", descr: "An empty & valid astTF file"},
]

function readme () :string {
  let result = ""
  // Root
  result += title_Root+Nl
  result += descr_Root+Nl
  result += Nl

  // Minimal Samples
  result += title_Minimal
  result += descr_Minimal+Nl
  for (const entry of entries) result += TemplEntry(entry.file, entry.descr)+Nl
  result += Nl

  // Basic Samples
  result += title_Basic
  result += descr_Basic+Nl
  result += TemplTODO
  result += Nl

  return result
}

//______________________________________
// @section Samples Generator: Entry Point
//____________________________
if (process.argv[1] === import.meta.filename) gen(trg)
function gen (trg :string) {
  F.write(trg, readme())
}
